### ISSUE TITLE
Question: Player to Nickname mapping information

### ISSUE THREAD

**Issue by ghost** [HecknTarnation/QuickNick#1]
Hello friend!!

Thank you so much for this awesome mod 😊

Question: If I wanted to see a player name to nickname mapping for all the players, what files would I need to inspect?

Thank you 🙇‍♂️

**Comment by HecknTarnation** [comment]
All player nickname data is stored in their persistent data, which is in the playerdata folder of the save. You will have to go through each of the player's NBT files to find their respective nickname. It's under the tag ForgeData/quicknick:nickname.
![Screenshot 2024-10-01 193518](https://github.com/user-attachments/assets/f081452a-dd51-4fb0-88f2-ef354a1dfe88)

**Comment by ghost** [comment]
> All player nickname data is stored in their persistent data, which is in the playerdata folder of the save. You will have to go through each of the player's NBT files to find their respective nickname. It's under the tag ForgeData/quicknick:nickname. ![Screenshot 2024-10-01 193518](https://private-user-images.githubusercontent.com/34589983/372681093-f081452a-dd51-4fb0-88f2-ef354a1dfe88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4OTIzOTQsIm5iZiI6MTcyNzg5MjA5NCwicGF0aCI6Ii8zNDU4OTk4My8zNzI2ODEwOTMtZjA4MTQ1MmEtZGQ1MS00ZmIwLTg4ZjItZWYzNTRhMWRmZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE4MDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNWQ5YTU1MTczY2ZkNjBjN2ViMmNiNjJjMGZlNDg2NDFlZDQxZjE5MWZlZjM3ZWFkNzVmYTE2MTIxMTAyNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P5R6B8eoGNBV5r_A-PWjhp_BMxcTJXRVCvm0_uTm27A)

This is super helpful! Thank you so much!! 😊
